name: Move PR Issues to Project Column

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  move-issues:
    uses: TransactionProcessing/org-ci-workflows/.github/workflows/move-linked-issue.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      project_column_name: "In Review"
      project_name_prefix: "Done"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
