name: Move PR Issues to Project Column

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  move-issues:
    runs-on: ubuntu-latest
        
    steps:
      - name: Get PR creation date
        id: pr_date
        run: |
          # Get the PR creation timestamp from the PR event
          PR_CREATED_AT="${{ github.event.pull_request.created_at }}"
          
          # Format it to get Month and Year
          MONTH_YEAR=$(date -d "$PR_CREATED_AT" +"%B %Y")
          echo "Month and Year: $MONTH_YEAR"
          
          # Set the project name prefix (e.g., "April 2025 Sprint Test")
          echo "project_name_prefix=$MONTH_YEAR Sprint Test" >> $GITHUB_ENV
      
      
      - name: Call Move Linked Issues to Project Column
        uses: TransactionProcessing/org-ci-workflows/.github/workflows/move-linked-issue.yml@main
        with:
          pr_number: ${{ github.event.pull_request.number }}
          project_column_name: "Done"
          project_name_prefix: ${{ env.project_name_prefix }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
